 Seq name: region6 
 Length of sequence: 15001 
 Number of predicted genes 5: in +chain 4, in -chain 1.
 Number of predicted exons 13: in +chain 11, in -chain 2.
 Positions of predicted genes and exons: Variant   1 from   1, Score:1813.750195 
   G Str   Feature   Start        End    Score           ORF           Len

   1 +    1 CDSo        79 -       423   56.73        79 -       423    345
   1 +      PolA       493                2.19

   2 +      TSS        563              -11.41
   2 +    1 CDSf       705 -      1426  251.18       705 -      1424    720
   2 +    2 CDSl      2198 -      3314  450.85      2199 -      3314   1116
   2 +      PolA      3366               -5.01

   3 -      PolA      5797                2.19
   3 -    1 CDSl      6110 -      6666   37.06      6110 -      6664    555
   3 -    2 CDSf      6720 -      8172  216.83      6721 -      8172   1452
   3 -      TSS       8238               -5.61

   4 +      TSS       8475               -2.91
   4 +    1 CDSf      8537 -      8554    3.63      8537 -      8554     18
   4 +    2 CDSi      8668 -      9043   64.84      8668 -      9042    375
   4 +    3 CDSi      9275 -     10371  290.12      9277 -     10371   1095
   4 +    4 CDSl     10543 -     12348  456.60     10543 -     12348   1806
   4 +      PolA     12607               -2.61

   5 +      TSS      12733               -7.61
   5 +    1 CDSf     13030 -     13262   22.47     13030 -     13260    231
   5 +    2 CDSi     13640 -     13749   14.97     13641 -     13748    108
   5 +    3 CDSi     14117 -     14132    3.67     14119 -     14130     12
   5 +    4 CDSl     14416 -     14428    1.35     14417 -     14428     12
   5 +      PolA     14466               -4.51

Predicted protein(s):
>FGENESH:[mRNA]   1   1 exon (s)     79  -    423   345 bp, chain +
ATGGCCGGTGAACGAGACGCATTTTCAGCGCACGCAAGGTACAGGATGGGCCGGGGACAC
GGCTGGTTGGACGTAGTACAGCGAGAGACCGCCGAAACAGGGCCGGTGACACGCGTCGCG
CATCGGGGGCCTCCTCCGAGCCCGACGTGGCCGCGCGCGCCGCCCGCGCCAGCGCACACG
TCGCCGTCCCACACGACGCTTCGAGGCCGGTTCACGCGTCGCCGTCCATTCCCAGGCCCC
GGCCCCCGCGCCCGCGCCGCACCGCCTCACGTTGCCTTCACCGGCGGAGCACGCGCCACG
TCCGCCCCCACCGCGCGCGCGCCACCTTTCATCGCCACTATTTAA
>FGENESH:   1   1 exon (s)     79  -    423   114 aa, chain +
MAGERDAFSAHARYRMGRGHGWLDVVQRETAETGPVTRVAHRGPPPSPTWPRAPPAPAHT
SPSHTTLRGRFTRRRPFPGPGPRARAAPPHVAFTGGARATSAPTARAPPFIATI
>FGENESH:[mRNA]   2   2 exon (s)    705  -   3314  1839 bp, chain +
ATGGCCCTCAACCTGACCCACCAGACCGGCGCTGCGGCCATCGCGGCCACGCCGGCGCCG
GGCGCGCGCGCTTCGGTGTTCGCGGCGGCCTCGCCCGCCGCCGCCGCCGCCGCCGGCTCC
GCCGTGGCGCCGGCGCAGGCGACCAGCCTGAGGATGCAGACGCAGCTGGTGGAGCCCGCG
CAGCCGCAGGCGCCGGAGATGTTCCAGGCCATGGCGCCCGACCAGCAGCAGCAGGGCGAG
GCCGCGCACCCGGACGCGGGCGGCGAGGAGGCACGCAAGGTGGGCGTGCCGGTGTTCGTG
ATGATGCCGCTGGACACGGTGCGCAAGGACGGCAGCGCGCTGAACCGGCGCAAGGCGGTG
CAGGCGTCCCTGGCGGCGCTCAAGAGCGCCGGCACGGCCGGCATCATGGTGGACGTGTGG
TGGGGCATCGCCGAGAGCGAGGGCCCCGGCCAGTACAACTTCGCCGGCTACATCGAGCTC
ATGGAGATGGCCAAGAAGGCCGGGCTCAAGGTGCAGGCCGTCATGTCTTTCCACCAGTGC
GGCGGCAACGTCGGAGACTCAGTCAAGTACGTCGTGCTCTGCTCCCTCTTCTCCATCCAG
TCCTCTGTCTATCCAAGTACACATATACGTACATGCATGCTGATCTTGATCATCCTTGCG
TACATTCTTGTATTTTTCCATGATTCCATGTACCATCGCATCTACGGGATGGACGCGTAC
ATCATACCACTTCCGAAATGGGTAACGGAGGAGATGGACAAGGACCAGGACCTGGCGTAC
ACGGACAGGTGCGGCCGCCGGAACTACGAGTACCTCTCGCTGGGCGCCGACACGATCCCG
GCCCTCAAGGGCCGCACCCCCATCCAGTGCTACGCCGACTTCATGCGCGCCTTCCGCGAC
CACCTCGCGCCCTACATGGGCAACACCATCTGCGAGATCCAGGTCGGCATGGGCCCCGCC
GGCGAGCTCCGCTACCCCTCCTACCCGGAGAGCAACGGCACCTGGTCCTTCCCCGGCATC
GGCGAGTTCCAGTGCTACGACCGCTACATGCGCGCCAGCCTCAAGGCCGCCGCCGAGGCG
GTGGGCAGGCCCGAGTGGGGCAACGCCGGCCCCGAGGACTCGGGCAGCTACAACCAGTGG
CCAGAGGACACCGGCTTCTTCCGCCGCGAGGGCGGCTGGAACACCGACTACGGCCAGTTC
TTCATGAGTTGGTACTCGCAGATGCTGATCGAGCACGGCGAGCGGATACTCTCCGCCTGC
TCCTCCGTCTTCACGGGTACCCCTGGGGTCAAGGTCTCCGTCAAGGTGGCCGGCATCCAC
TGGCACTACGGCACCCGCTCCCACGCGCCCGAGCTCACCGCCGGCTACTACAACACCAGG
AACCACGACGGGTACCTGCCCATCGCGCGCATGATCGGTCGCCACGGCGCCGTGCTCAAC
TTCACCTGCGTCGAGATGCGCAACCACGAGCAGCCGCAGGACGCGCAGTGCATGCCCGAG
GCGCTCGTGAGCCAGGTGGCCAGCGCCGCCAAGGAGGCCGGAGTGGGCCTCGCCGGGGAG
AACGCCCTACCCAGGTACGACGAGACGGCGCACGACCAGGTGCTGGCCACCGCGGCGGAG
AAGGCTGAGGAGGACCGCATGGTCGCCTTCACCTACCTTCGCATGGGCCCCGACCTCTTC
CAGCCCGACAACTGGCGCCGCTTCGCCGCGTTCGTCAAGCGCATGACGGAGACCGGCGTC
AGGGACGTGAGCCGGGAGCAGGTGGAGCGCGAGGCTCAGGGCGTCGCCCACGCCACCCAG
GGCGTCATCCAGGAGGCCGCCGTCGCCCTCTGCAACTAA
>FGENESH:   2   2 exon (s)    705  -   3314   612 aa, chain +
MALNLTHQTGAAAIAATPAPGARASVFAAASPAAAAAAGSAVAPAQATSLRMQTQLVEPA
QPQAPEMFQAMAPDQQQQGEAAHPDAGGEEARKVGVPVFVMMPLDTVRKDGSALNRRKAV
QASLAALKSAGTAGIMVDVWWGIAESEGPGQYNFAGYIELMEMAKKAGLKVQAVMSFHQC
GGNVGDSVKYVVLCSLFSIQSSVYPSTHIRTCMLILIILAYILVFFHDSMYHRIYGMDAY
IIPLPKWVTEEMDKDQDLAYTDRCGRRNYEYLSLGADTIPALKGRTPIQCYADFMRAFRD
HLAPYMGNTICEIQVGMGPAGELRYPSYPESNGTWSFPGIGEFQCYDRYMRASLKAAAEA
VGRPEWGNAGPEDSGSYNQWPEDTGFFRREGGWNTDYGQFFMSWYSQMLIEHGERILSAC
SSVFTGTPGVKVSVKVAGIHWHYGTRSHAPELTAGYYNTRNHDGYLPIARMIGRHGAVLN
FTCVEMRNHEQPQDAQCMPEALVSQVASAAKEAGVGLAGENALPRYDETAHDQVLATAAE
KAEEDRMVAFTYLRMGPDLFQPDNWRRFAAFVKRMTETGVRDVSREQVEREAQGVAHATQ
GVIQEAAVALCN
>FGENESH:[mRNA]   3   2 exon (s)   6110  -   8172  2010 bp, chain -
ATGGCAATTTTCTGTCAAAAAAATGAAAAAGGACAAAGTTGCCATCCCCTATCAATTAAA
GTTGCCATCCCCGTGCTCCCCTTCAGCACGGCGGGGCTGTTCGGTGAACTGAAGAGCAAG
TGGGGGCTGCGCGGACGGCTCGACTACACACCTCTCCGCAACAACCGCTTCATGCTCGAA
TTCGAGCGTGAGGGCGATCGTCAGCACGTCCTGGAAAACGGCCCATGGACACACCGTAAG
GATGCATTCCTCATTGTTCCCTTTGATGGACAGGGCAAGGCGTCGGACGTACCGGTGAAC
GTCATGCCAATCTGGGCACGCATCTATGATGTGCCACCTCTCATGCTGTCAGAAGAGATC
GGGTGGAAGCTAGGTGGCCTCTTGGGAAAAGTTCTCAGGGTAGATGCGGATAAGTTTGGG
AATATTTTCTCTGAATTTCTTTGTGTAAGAGTTGAACATAATGTAAACACTCCTCTCCTG
CGTGAGATCAGTCCTAGAGAGTTAGGGGAGAAAGAGCATATGGACCTAGAGGTCAAGTAT
GAGAGAGCCCCACGATTTTGTATGTACTGTGGGCACATAGGTCATGGGGAAAGGGACTGC
AGGCTGCCGACGGATGATCAAGCAGAGAGGTTCACGGGGGCGATGAGAGCATTGCCCTAT
AAATCAAGCAAAAACAAGTGCGGCTTCGTGGTACCAGACGCTTGTAGTGCCAGACGCTTC
CTGCACTTTGGGTCTGAGTTGGACGGGGAGGCATGGACAGCCCCGGCCAAATTGGCCTGG
GAGAAGCTAGGCAGAGACAAGAAGGTGATGCATGCTCGATCACAGGAGATGGTAAGATGC
AGGGATATTCCAGATGATGTGCTGCTGGACCCGGCTGTACAAGCGGCAATCGCAGCGGTT
AGCGCGCTTAGAGTGAGCGAAGACACTGGAAATGAAGGCACCAGGAAGACGAGCATCGGC
GAGAACACAAAGATGGCTCCGGCGAAACCCGCGCTGACCACGGCTTCTACTCCAACCATA
GCCATGGCTGACGCGGACACCTCGCCATCTACACCACCGGGTACAGGGGCGGGGGGCGAC
ATCGACAAAACCCCGCTCGCACACACCATCGAGGATGCAGCAACCCCTCCCTACCCGCCG
GGTTTCGAGCCCGACTCTGTTAAGGCCTCTCCTGTCGCTGCTACTGTTAACTCAGTAGAG
ACGGAGACAAAGTCAGGGAAGTTGCATGCACCAAAAGGAACAGGTCTCAAAACCAAGGCA
AAATATATTAGCCAGCTCAAGGAAAGAAAGGAACCAGGGGAGACAAATTCAGTTCTAGGA
AAAAGAGGCACGGGTGACATGGCCACATCTACTGGGGCTATGGCTAGTGCGTCTGATGTA
ACAGGGGACATGTATAAGAAACAGAGAGCTGCTGTAGAGGAAGAGGATGAGAGAGCTGTA
GGAGAGATAGGTGAGCGCCCGTCAGGAGGAATGACGATCCTATGTTGGAACTGCCGGGGA
CTGGGCCACCCCGGGACAGTTCGTGAGCTTGTGTGCCTAGTGCGCACGTACCGCCCCTCT
GTCGTGTTCATCTCTGAGACGCGGCAGTGTGAGGAGAGCGTCAAAAGAATAAGATGGAGG
CTGGGCCTCAAAAACTGCATCACCCACGATGGCATGGGAAAAGGTGCTGGTATAGCCCTG
TTTTGGGATGAAAGTGTTGAAATAAAATTACTCTCCTATGGTTTGAGGTATATTGATGTG
CATATGCGTATGGATCCCCATGGCCCGATGTGGCGGGGTACCTTTGTGTACGGCGAGCCT
AGAGCACATGAGAGGCATAACATGTGGAACCTGCTGAAAAGAATAAAACCAAAATCGATT
GAGCCGTGGATGATGATAGGAGACTTCAATGAAACATTATGGCAAAGTGAACATTTCTCT
GCAGCAAAAAGATCTGAAAGGTATATGGGCAATTTCAGAGATGTACTGGCATACTGTAAT
CTTCATGATCTGGGTTACCATGGTTGGTAG
>FGENESH:   3   2 exon (s)   6110  -   8172   669 aa, chain -
MAIFCQKNEKGQSCHPLSIKVAIPVLPFSTAGLFGELKSKWGLRGRLDYTPLRNNRFMLE
FEREGDRQHVLENGPWTHRKDAFLIVPFDGQGKASDVPVNVMPIWARIYDVPPLMLSEEI
GWKLGGLLGKVLRVDADKFGNIFSEFLCVRVEHNVNTPLLREISPRELGEKEHMDLEVKY
ERAPRFCMYCGHIGHGERDCRLPTDDQAERFTGAMRALPYKSSKNKCGFVVPDACSARRF
LHFGSELDGEAWTAPAKLAWEKLGRDKKVMHARSQEMVRCRDIPDDVLLDPAVQAAIAAV
SALRVSEDTGNEGTRKTSIGENTKMAPAKPALTTASTPTIAMADADTSPSTPPGTGAGGD
IDKTPLAHTIEDAATPPYPPGFEPDSVKASPVAATVNSVETETKSGKLHAPKGTGLKTKA
KYISQLKERKEPGETNSVLGKRGTGDMATSTGAMASASDVTGDMYKKQRAAVEEEDERAV
GEIGERPSGGMTILCWNCRGLGHPGTVRELVCLVRTYRPSVVFISETRQCEESVKRIRWR
LGLKNCITHDGMGKGAGIALFWDESVEIKLLSYGLRYIDVHMRMDPHGPMWRGTFVYGEP
RAHERHNMWNLLKRIKPKSIEPWMMIGDFNETLWQSEHFSAAKRSERYMGNFRDVLAYCN
LHDLGYHGW
>FGENESH:[mRNA]   4   4 exon (s)   8537  -  12348  3297 bp, chain +
ATGGAGATCCCTGACCAGACCAATCCGTGCGCGATCTGTCTCAGCGGCATGGGCGCCGGC
GGTGGTCAGGCCACCTTCACGGCGGAGTGCTCCCACACGTTTCACTCCAGCTGCATCTCC
GCCAGCGTCTGCCCGCTCTGCAGCGTGCCGCGGTACGACCTGCCGTTCCGGCGACCCACA
CCACCTCCACCTCCGCCGCCCCCGCCGGTGCGACCTCAGCCAGAGACTCGTCCCATTCCC
CTCCGCCCGTGCATCATTCTCCCGCGGCAGTCACCTCCCGTGCATTTCGTGCACGGTCAG
CCACCGCCACCGCCACCACGACCGACATACTCGTGGCCACGCATTCCCACGCAGGCACGA
CAGCCGCCGCCACGGCCCGTGAATCTCGTGCACGCTGGCAACCGGTCACCAGCCGCTGCA
TCAAACGAAGCAGTTGTCATCAAGACGCGAAGCGAGTACCCGGCCATCGCCATGGATTTG
TCCAGCGACAACTTCGCCGTGCTCGTGCACGTCCAGGCTCCCGGGATGACCGACATCACG
GCAGCCGGTGGCGACGCGCCGCGCGCGCCGGTGGACCTCGTGACGGTTCTCGATGTCAGT
CACAGTATGAGCGGGCAAAAGTTGACGCTGTTGAAGCAGGCCATGCGGTTCGTCATCGCC
AATCTCGGCCCCGACGACCGCCTCTCCGTCGTGTCCTTCAACACGAAGGCGCGCCGGGTG
ACCAGGCTCACGCGCATGTCGGAGGCCGGGAAGGCCCTGTCCGTGAGCGCTGTGGAGTCC
CTCACGGCGGGCGGCTGCACCGACATCGCCGAGGGGCTCCGTATGGCAGCCATGGTACTC
GACCAGCGCCGGCACAGGAACGCCGTCTCGAGCGTCGTGCTCCTCTCTGATGGCCAGGAC
AACTACATCATGATGAGGCACCAGGAGTCGTCCGGTGTCCAGGCCAACGACTACGAGGAC
CTCGTCCCGCCCACCTTCGCGCGCACGGGCGCTGACGGCGAATGGTCAGCATCGATCCAC
ACTTTCGGCTTCGGCAATGACCATGACGCGACCGCGATGCACGTCATCGCCGAGGCTACA
GGCGGCACGTTCTCGTTCGTAGAGAACGAGGCGATGATCCAGGACGCGTTCGCACAGTGC
ATCGGCGGGCTGCTCTCTGTCGTGGTCCAGGAGGCTCGCATCGCCGTCGCGTGCGTGCAC
CCCGGGGTCCGTGTCATGTCGGTCAAGTCCGGCAGTTACGAGAGCCGCATCGACGAGGAC
GGCCGCGCCGCCACGGTCTGGGTCGGAGAACTATACGCTGATGAGGAGAGGCGTTTCTTG
CTGATCCTGACCGTGCCAAGAGCCGAAGCGACAGACGGTGACACCACCGCTCTGTTGAAT
GTGTCATTCAGCTGCAGAGACGCGGCGACCGGCATGGACGTGAACGTGTCGGCCAAGGAT
ACACTGGTGGCGAGGCCGGAGCACGCCGTGGACGCGAAGCGGTCGGTGGAGGCCGAGCTG
CAAGAGATGCGCGGGCGCGTGTCGAACCGACAGAGCTACGCGTTGTCGGGTCGGGCGTAC
ATGCTCGCCGGCATCAGCGCGCACCAGCAGCAACGCGCTACCTCGAGGCAGATGAATCTG
GTGGAGGAGATGTCGGTGGAATTTATGGCCGCACTGGTGGCGGCGCCGCCAGTGAAGTTG
GCATCGAACGAGGCGACATTGTCGTACGCGACGCCGGCTATGCGCGCCATGCTGCTACGC
TCGCGTAGGGCACGGGAGGCATCAGCCGAGCAAGGGCAGCAACTACAAGCTGAAGAAGAA
TACACAGGAAGCTCTAAACACGGTCAGCCAACGCCGCCACTGACATCGTCGTGTCCCCGC
TTGCCCACGCAGCTACGTCCGCCACCGCCACCACCCATGCGTATCGGGCATGCTCGGCCG
CCTACGGTTGTCTTCGACGACGACGAGCAGGGTGGTCCGGCCTCTGGGCCGCCAGCTGAC
AACCGGTCACCAGCCGCCGCGTCGAACGAAGCAGTTGTCGTCAAGACGCGGAGCGAGTAC
CCGGCCATCGCTAGGGATTCGTCCAGTGAAAACTTCGCCATGCTCGTGCACGTCCAGGCT
CCCGGGATGACCGACATCATGGCGGTTGGTGGCGACGCGTCGCGCGCGCCGGTGGACCTC
GTGACGGTTCTCGACGTCGGTGGCAGCATGAGCGGGTACAAGCTGGCGCTGCTGAAGCAG
GCCATGCGGTTCATCATCGCCAATCTTGGCCCCGGCGACCGCCTCTCCGTCGTGTCCTTC
TCCTCCGTGGCGCGCCGCCGGACCAGGCTCACGCTCATGTCGGAGACCGGGAAGGCCCTG
TCCGTGAGCGCCGTGGAGTCCCTCACGGCGGGCGGCGGCACCGACATCGCCGAGGGGCTC
CATATGGCAGCCATGGTACTCGACCAGCGTCGGCACAGAAACGCCGTCTCTAGCGTCGTG
CTCCTCTCCGACGGCCCAGGGTCATCCGGCGTCCGGGCCAACAACTACGAGGAGCTCGTC
CCGCCCTCCTTCGCACGCACGGGAGCTGACGGCGAATGGTCAGCGCCGATCCACACGTTC
GGCTTCGGCAACGACCACGACACGGCCGCGATGCACGCCATCGCCGACGCGACGGGCGGC
ACGTTCTCGTTCATCGAGAACGAGGCGGTGATCCAGGACGCGTTTGCCCAGTGCATCGGC
AGGCTGCTCTCCGTCGTGGTCCAGGGGGCTCGCATCGCCGTCGCGTGCGTGCACGCCGGG
GTCCGTCTCATGTCGGTGAAGTCTAGCAGTTATGAGAGCCGCATCGACGAGGACGGCCGC
GCCGCCACGGTCTGTATCGGGGAACTCTACGCCGAGGAGGAGAGGCGTTTCTTGCTGTCT
CTGGCCGTGCCAAGAGCTGAAGCAACAGACGGCGACACCGCTACTCTGGTGAAAGTGGTG
TTCAGCTACAGAAACGCGACGACCGGCGCGGACGTGAGCGTGACAACGGAGGACACAGTG
GTGGCGAGGCCGGAGCACGCGCCGAACGCATCGGAGCGGTCGGTAGAGGTGGAGCGGGAG
CGCATCCGGGTGGAGGCGGCAGAGGACTTCACGGCGGCGAGGGCAGCGGCGGAACGGGGC
GACCACCGGGAGGCGGTGAAGATACTCAACAACCGGCAGCGTGCAGTGGCGCTGTCACAG
TTGTCGCGCGACGACGACCCCGTGATCATGGCGCTGGAGGCCGAGCTGTGGGGGATGTGC
GGGCGCGTGGCGAACCGGCAGAGATACGCGCGGCCGGGTCCGGCGTACATGCTTTAG
>FGENESH:   4   4 exon (s)   8537  -  12348  1098 aa, chain +
MEIPDQTNPCAICLSGMGAGGGQATFTAECSHTFHSSCISASVCPLCSVPRYDLPFRRPT
PPPPPPPPPVRPQPETRPIPLRPCIILPRQSPPVHFVHGQPPPPPPRPTYSWPRIPTQAR
QPPPRPVNLVHAGNRSPAAASNEAVVIKTRSEYPAIAMDLSSDNFAVLVHVQAPGMTDIT
AAGGDAPRAPVDLVTVLDVSHSMSGQKLTLLKQAMRFVIANLGPDDRLSVVSFNTKARRV
TRLTRMSEAGKALSVSAVESLTAGGCTDIAEGLRMAAMVLDQRRHRNAVSSVVLLSDGQD
NYIMMRHQESSGVQANDYEDLVPPTFARTGADGEWSASIHTFGFGNDHDATAMHVIAEAT
GGTFSFVENEAMIQDAFAQCIGGLLSVVVQEARIAVACVHPGVRVMSVKSGSYESRIDED
GRAATVWVGELYADEERRFLLILTVPRAEATDGDTTALLNVSFSCRDAATGMDVNVSAKD
TLVARPEHAVDAKRSVEAELQEMRGRVSNRQSYALSGRAYMLAGISAHQQQRATSRQMNL
VEEMSVEFMAALVAAPPVKLASNEATLSYATPAMRAMLLRSRRAREASAEQGQQLQAEEE
YTGSSKHGQPTPPLTSSCPRLPTQLRPPPPPPMRIGHARPPTVVFDDDEQGGPASGPPAD
NRSPAAASNEAVVVKTRSEYPAIARDSSSENFAMLVHVQAPGMTDIMAVGGDASRAPVDL
VTVLDVGGSMSGYKLALLKQAMRFIIANLGPGDRLSVVSFSSVARRRTRLTLMSETGKAL
SVSAVESLTAGGGTDIAEGLHMAAMVLDQRRHRNAVSSVVLLSDGPGSSGVRANNYEELV
PPSFARTGADGEWSAPIHTFGFGNDHDTAAMHAIADATGGTFSFIENEAVIQDAFAQCIG
RLLSVVVQGARIAVACVHAGVRLMSVKSSSYESRIDEDGRAATVCIGELYAEEERRFLLS
LAVPRAEATDGDTATLVKVVFSYRNATTGADVSVTTEDTVVARPEHAPNASERSVEVERE
RIRVEAAEDFTAARAAAERGDHREAVKILNNRQRAVALSQLSRDDDPVIMALEAELWGMC
GRVANRQRYARPGPAYML
>FGENESH:[mRNA]   5   4 exon (s)  13030  -  14428   372 bp, chain +
ATGCCGGTGAATGGGAATATGGCCATGTTCAAGCGAGGACACCGGGCTCAGCTGCTTGTG
CCCGAGACGCTGGTCGAGAACATGCTATTCCTCGCTGTTGGCATGCGCGTGGAACTCAAT
AAGATGGTGAAGGAGGGTAGGGAGCTAAGAGGATACTGGTACCTGCTCCCAGCGTGGAGC
TGCGCAATGCATGCGCTGTTGGAGTTAACCACGTCGGAGAGTCCATGCCCGGTCTATACC
GCCGTTGAGGTCGGACCAGCGCCAACAGCGATGGTGGCCGGGCTCGTCAAAGTGCAGGTG
GCGATGGCGTCAGTGGGGCGGCGCATCCCCCGGGACAGCGAACGTGGGTCCTTCGTAAGG
AAAAAAAAGTAG
>FGENESH:   5   4 exon (s)  13030  -  14428   123 aa, chain +
MPVNGNMAMFKRGHRAQLLVPETLVENMLFLAVGMRVELNKMVKEGRELRGYWYLLPAWS
CAMHALLELTTSESPCPVYTAVEVGPAPTAMVAGLVKVQVAMASVGRRIPRDSERGSFVR
KKK